README.md

Added go-doc, report-card and License to readme

---

routes.go

Removed debug statements

---

README.md
docs/metrics.md
go.mod
go.sum
pkg/localmetrics/localmetrics.go
routes.go
server_test.go

Added metrics docs and copyright header

---

README.md

fix readme link for metrics

---

docs/metrics.md

Fix metrics docs

---

.travis.yml
server_test.go

Signed-off-by: Jack Ding <jacding@redhat.com>

Add travis to GitHub CI

---

README.md
docs/metrics.md
go.mod
go.sum
pkg/localmetrics/localmetrics.go
routes.go
server_test.go

Fixed status ping and metrics.
Added more test for server pai

Added status ping and metrics

---

go.mod
go.sum

Signed-off-by: Jack Ding <jacding@redhat.com>

Upgrade to go 1.17

---

go.mod
go.sum

Signed-off-by: Jack Ding <jacding@redhat.com>

Update sdk-go version

---

go.mod
go.sum

Signed-off-by: Jack Ding <jacding@redhat.com>

Update sdk-go module

---

go.mod
go.sum

Update go-sdk dependency

---

go.mod
go.sum
vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
vendor/modules.txt

Fix http issue with go-sdk

---

go.mod
go.sum
vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go
vendor/modules.txt

Updated sdk

---

go.mod
go.sum
routes.go
server.go
server_test.go
vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go
vendor/modules.txt

* Add vendor files
* currentState implmentation for http add rest api for currentstate (works for http only)

[release-4.12] cherry pick :Current status rest api implementation (#34)

---

go.mod
go.sum
routes.go
server.go
server_test.go
vendor/github.com/redhat-cne/sdk-go/v1/pubsub/pubsub.go
vendor/modules.txt

update go SDK  to Add functionality to get status via CurrentState rest api call

BUG OCPBUGS-1605: Event Pull Status Notification GET Method not working as per o-Ran spec

---

.golangci.yaml
go.mod
go.sum
vendor/github.com/redhat-cne/sdk-go/pkg/event/event_unmarshal.go
vendor/modules.txt

lint enhancement and go-sdk-update

---

go.mod
go.sum
vendor/modules.txt

update sdk to fix amq event send

update go sdk to fix send event bug

---

go.mod
go.sum
vendor/modules.txt

go sdk update

---

go.mod
go.sum
vendor/modules.txt

update sdk-go version for amq race-condition fix

---

go.mod
go.sum
vendor/modules.txt

4.12 update sdk-go version for amq race-condition fix

---

go.mod
go.sum
vendor/modules.txt

4.11 update sdk-go version for amq race-condition fix

---

go.mod
go.sum

4.10 update sdk-go version for amq race-condition fix

---

go.mod
go.sum
vendor/modules.txt

update sdk-go version for amqp resource leak

---

go.mod
go.sum
vendor/modules.txt

update sdk-go model for increasing amq timeout

---

go.mod
go.sum
vendor/modules.txt

[release-4.11] update sdk-go model for increasing amq timeout

---

go.mod
go.sum

[release-4.10] update sdk-go model for increasing amq timeout

---

go.mod
go.sum
vendor/modules.txt

update sdk-go version for amq configurable timeout

---

go.mod
go.sum
vendor/modules.txt

[release-4.12] update sdk-go version for amq configurable timeout

---

go.mod
go.sum
vendor/modules.txt

[release-4.11] update sdk-go version for amq configurable timeout

---

go.mod
go.sum

[release-4.10] update sdk-go version for amq configurable timeout

---

go.mod
go.sum
vendor/github.com/redhat-cne/sdk-go/pkg/channel/doc.go
vendor/github.com/redhat-cne/sdk-go/pkg/channel/pipeline.go
vendor/github.com/redhat-cne/sdk-go/pkg/channel/types.go
vendor/github.com/redhat-cne/sdk-go/pkg/event/event.go
vendor/github.com/redhat-cne/sdk-go/pkg/event/event_ce.go
vendor/github.com/redhat-cne/sdk-go/pkg/event/event_data.go
vendor/github.com/redhat-cne/sdk-go/pkg/event/event_writer.go
vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub.go
vendor/github.com/redhat-cne/sdk-go/pkg/types/value.go
vendor/github.com/redhat-cne/sdk-go/pkg/util/wait/wait.go
vendor/modules.txt

update sdk-go for http restart fix

---

go.mod
go.sum
vendor/modules.txt

update sdk-go for fix subscriber delete via k8s service

---

go.mod
go.sum
vendor/github.com/redhat-cne/sdk-go/pkg/store/store.go
vendor/modules.txt

This pull new changes to SDK for HTTP subscription changes to fix delete and ack of cloudevents http calls

update sdk for subscription delete changes

---

go.mod
go.sum
routes.go
server_test.go
vendor/github.com/redhat-cne/sdk-go/pkg/channel/data.go
vendor/modules.txt

Update SDK and used new sdk  validation error message

Add current state validation  for subscriptions

---

v2/server_test.go

add O-RAN v3.0 API compliance tests according to O-Cloud Conformance Test Specification (O-RAN.WG6.O-CLOUD-CONF-Test-R003-v02.00)

add O-RAN v3.0 API compliance tests

---

.gitignore
go.mod
go.sum
v2/routes.go
v2/server.go
v2/server_test.go
vendor/github.com/redhat-cne/sdk-go/pkg/event/ptp/resource.go
vendor/github.com/redhat-cne/sdk-go/pkg/pubsub/pubsub_unmarshal.go
vendor/github.com/redhat-cne/sdk-go/v1/subscriber/subscriber.go
vendor/modules.txt

Cherry-pick from main branch:
- add checking of mandatory fields in pubsub (#86)
- fix subscription for multiple clients (#85)
- add O-RAN v3.0 API compliance tests (#82)

Fix subscription error cases and add O-RAN compliance tests
